- name: Build WAR on workstation and deploy to target server
  hosts: localhost
  vars:
    repo_url: "https://github.com/Ashu2356/project.git"
    repo_dest: "{{ lookup('env','WORKSPACE') }}/project"
    war_file_name: "LoginWebApp.war"
    target_host: "172.31.38.202"
    target_tomcat_path: "/opt/tomcat/webapps"

  tasks:
    - name: Remove old project directory if exists
      file:
        path: "{{ repo_dest }}"
        state: absent

    - name: Clone project repository on workstation
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "master"
        force: yes
        depth: 0
        update: yes

    - name: Show repo_dest path
      debug:
        var: repo_dest

   - name: Build WAR using Maven
  command: mvn clean package -X
  args:
    chdir: "{{ repo_dest }}"
  environment:
    JAVA_HOME: "/usr/lib/jvm/java-17-amazon-corretto.x86_64"
    PATH: "/usr/lib/jvm/java-17-amazon-corretto.x86_64/bin:{{ lookup('env','PATH') }}"
  register: maven_build
  failed_when: "'BUILD SUCCESS' not in maven_build.stdout"
  
    - name: Copy WAR file to target host
      ansible.builtin.copy:
        src: "{{ repo_dest }}/target/{{ war_file_name }}"
        dest: "{{ target_tomcat_path }}/{{ war_file_name }}"
        owner: tomcat
        group: tomcat
        mode: '0644'
      delegate_to: "{{ target_host }}"

    - name: Restart Tomcat service on target host
      ansible.builtin.systemd:
        name: tomcat
        state: restarted
      delegate_to: "{{ target_host }}"
